runtime: nodejs18

handlers:
  - url: /.*
    script: auto
  - url: /uploads
    static_dir: uploads

env: standard
env_variables:
  DB_USER: 'your-cloud-sql-username'
  DB_PASSWORD: 'your-cloud-sql-password'
  DB_HOST: 'your-cloud-sql-instance-ip'

